### ISSUE TITLE
Obstáculos (Tubo/Canos)

### ISSUE THREAD

**Issue by juliano-mesquita** [juliano-mesquita/FlappyBird-408T-2024-2#1]
Como jogador, quero obstáculos visuais claros e consistentes que adicionem desafio ao jogo.

**Tarefas:**
- Criar sprite de cano/tubo superior e inferior.
- Criar sprites de diferentes alturas para gerar variação visual nos obstáculos.
- Adicionar pequenos detalhes nos canos (ex.: textura, cor) para diferenciar dos tubos do Flappy Bird.

Critérios de aceitação:
- Layout criado no Figma
- Aprovação da turma com os Sprites Criados

**Comment by AllanZaitz** [comment]
https://www.figma.com/design/pwLSzY6CEpBqoFVBMyDoI6/Estaca-AG?node-id=0-1&node-type=canvas&t=hO8Y0nlTWTr6OeNp-0

**Comment by AllanZaitz** [comment]
https://www.figma.com/design/pwLSzY6CEpBqoFVBMyDoI6/Estaca-AG?node-id=10-563&node-type=frame&t=P8ruVdqQBlMv25wp-0
