### ISSUE TITLE
Configuração do Firestore para Armazenar Pontuações

### ISSUE THREAD

**Issue by juliano-mesquita** [juliano-mesquita/FlappyBird-408T-2024-2#16]
**Tarefa 1: Criar Estrutura de Dados para Scoreboard no Firestore**

- No Firebase Firestore, criar uma coleção chamada scores ou scoreboard.
- Definir os campos necessários em cada documento, como:
username: nome do jogador.
score: pontuação do jogador.
timestamp: data e hora da partida para fins de ordenação.
**Tarefa 2: Configurar Regras de Segurança do Firestore**

- Configurar regras para permitir apenas leitura e escrita seguras.

**Critérios de Aceitação:**

- A estrutura scoreboard está configurada e pronta para armazenar os dados de pontuação.
- As regras de segurança permitem operações seguras e específicas para o projeto.

**Comment by agsjohn** [comment]
Só vou precisar dos email para adicionar ao Firebase
