### ISSUE TITLE
Personagem Principal (Pássaro ou Outro Animal Voador)

### ISSUE THREAD

**Issue by juliano-mesquita** [juliano-mesquita/FlappyBird-408T-2024-2#2]
Como jogador, quero um personagem principal, com animações, para controlar durante o jogo.

**Tarefas:**

- Criar sprite do personagem em uma posição neutra (voo).
- Desenhar animações para:
   - Pulo/Voada: uma leve animação para quando o jogador toca na tela.
   - Queda: uma animação leve para a queda do personagem, com uma leve rotação.
- Criar variações de cor do personagem para eventual customização.

Critérios de aceitação:
- Layout criado no Figma
- Aprovação da turma com os Sprites Criados

**Comment by juliano-mesquita** [comment]
Link do figma com personagem e animações:

**Comment by InkySaaS** [comment]
![flappybird](https://github.com/user-attachments/assets/c530f026-5e2a-4a75-9e53-1e3da6434e8c)
Placeholder, terá outra versão

**Comment by SaraSerafimUrruzola** [comment]
![flappybird](https://github.com/user-attachments/assets/9de46a4d-a104-4e07-9e54-ac1af736f1e4)
![flappybirdalt](https://github.com/user-attachments/assets/8c891b20-8413-4dd3-b58a-2c6f5ea5896c)
Placeholder, será atualizado posteriormente.
