### ISSUE TITLE
Cenário de Fundo

### ISSUE THREAD

**Issue by juliano-mesquita** [juliano-mesquita/FlappyBird-408T-2024-2#3]
Como jogador, quero um cenário de fundo agradável que se mova durante o jogo, criando uma sensação de progressão.

Tarefas:
- Criar um cenário básico (ex.: céu com nuvens).
- Adicionar detalhes como montanhas ou árvores ao fundo para dar mais profundidade.
- Criar camadas de fundo para efeito de **parallax** (ex.: céu, nuvens e montanhas em camadas separadas).
- Garantir que as camadas do cenário possam ser repetidas sem falhas visuais.

Critérios de aceitação:
- Layout criado no Figma
- Aprovação da turma com os Sprites Criados

**Comment by g4bcs** [comment]
[https://www.figma.com/design/1ru39YoyhghTDrUsMlM20m/Flappy-bat?node-id=0-1&t=Ru5GZxhBlg5aDQ2f-1](url)

**Comment by g4bcs** [comment]
https://www.figma.com/design/1ru39YoyhghTDrUsMlM20m/Flappy-bat?node-id=0-1&m=dev&t=Ru5GZxhBlg5aDQ2f-1
