### ISSUE TITLE
Chão e Superfície Inferior

### ISSUE THREAD

**Issue by juliano-mesquita** [juliano-mesquita/FlappyBird-408T-2024-2#4]
Como jogador, quero uma área de chão visível para evitar colisões e aumentar a percepção do ambiente.

Tarefas:
- Criar sprite de chão com textura simples.
- Adicionar pequenos detalhes, como grama ou pedras, para mais realismo.
- Configurar o chão para se mover horizontalmente de forma contínua, sem quebras.

Critérios de aceitação:
- Layout criado no Figma
- Aprovação da turma com os Sprites Criados

**Comment by logben600** [comment]
https://www.figma.com/design/6xOVq0cARpIMKU0s2d7P2U/ch%C3%A3o?node-id=0-1&node-type=canvas&t=GPJL0HukEu1dh3UJ-0
