### ISSUE TITLE
Sons e Efeitos

### ISSUE THREAD

**Issue by juliano-mesquita** [juliano-mesquita/FlappyBird-408T-2024-2#5]
Como jogador, quero ouvir efeitos sonoros que acompanhem as ações do jogo, para uma experiência mais envolvente.

Tarefas:
- Criar efeito sonoro para o pulo do personagem.
- Adicionar efeito de colisão.
- Incluir som de pontuação ao ultrapassar um obstáculo.

**Comment by PauloFernando-bit** [comment]
->Som de moeda:
https://github.com/user-attachments/assets/6629638d-4ee8-4312-b1ec-7a578ad31e81

->Som de Bater de Asas:
https://github.com/user-attachments/assets/f1701c3d-3bc6-4ca4-bf24-88efdc528aac

->Trilha Sonora:
https://github.com/user-attachments/assets/f396955a-604c-4a5a-8fb2-c8b90d255e70

->Som de Derrota:
https://github.com/user-attachments/assets/73da95fc-57d8-435d-81b8-e3601bf0f83b
