### ISSUE TITLE
Interface de Usuário (UI)

### ISSUE THREAD

**Issue by juliano-mesquita** [juliano-mesquita/FlappyBird-408T-2024-2#6]
Como jogador, quero uma interface clara e minimalista para acompanhar minha pontuação e interagir com o jogo.

Tarefas:
- Criar Design das telas e fluxo de navegação

Critérios de Aceitação:
- Layout no Figma

**Comment by IgorChassot** [comment]
https://www.figma.com/design/yxA5Oh2UlifdyZkY9GpqJ6/Flappy-Bird-UI?node-id=3-5&t=aAFPekPqdRre5fdG-1
