### ISSUE TITLE
Configuração do Game Loop Básico

### ISSUE THREAD

**Issue by juliano-mesquita** [juliano-mesquita/FlappyBird-408T-2024-2#9]
Como desenvolvedor, quero configurar o loop de jogo para gerenciar os ciclos de atualização e renderização.

Tarefas:
- Criar uma classe básica que estenda FlameGame para o loop de jogo.
- Implementar os métodos onLoad, update, e render para carregar, atualizar, e desenhar o jogo.
- Adicionar a instância do FlameGame ao runApp do Flutter para executar o loop.
- Testar se o loop está funcionando imprimindo logs ou exibindo um fundo colorido temporário.

**Comment by agsjohn** [comment]
import 'package:flame/game.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class MyGame extends FlameGame {
  @override
  Future<void> onLoad() async {
    super.onLoad();
    if (kDebugMode) {
      print('Jogo carregado');
    }
  }

  @override
  void update(double dt) {
    super.update(dt);
    if (kDebugMode) {
      print('Update: $dt');
    }
  }

  @override
  void render(Canvas canvas) {
    super.render(canvas);
    Paint cor = Paint();
    cor.color = Colors.white;

    canvas.drawCircle(Offset(size.x / 2, size.y / 2), 100, cor);
  }
}

void main() {
  runApp(
    GameWidget(game: MyGame()),
  );
}

**Comment by agsjohn** [comment]
```
import 'package:flame/game.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class MyGame extends FlameGame {
  @override
  Future<void> onLoad() async {
    super.onLoad();
    if (kDebugMode) {
      print('Jogo carregado');
    }
  }

  @override
  void update(double dt) {
    super.update(dt);
    if (kDebugMode) {
      print('Update: $dt');
    }
  }

  @override
  void render(Canvas canvas) {
    super.render(canvas);
    Paint cor = Paint();
    cor.color = Colors.white;

    canvas.drawCircle(Offset(size.x / 2, size.y / 2), 100, cor);
  }
}

void main() {
  runApp(
    GameWidget(game: MyGame()),
  );
}
```

**Comment by juliano-mesquita** [comment]
Depende de: #7
